# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ac1816a-311a-40f7-a788-13a4521ccfc8";
      fsType = "ext4";
    };

  fileSystems."/mnt/disk02" =
    { device = "/dev/disk/by-uuid/b61d6740-6247-4823-8d88-f290a2be6595";
      fsType = "ext4";
      options = [ "defaults" "nofail"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b807a43d-d26e-4b74-927b-ddd958b52dc5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
